version: '3.7'

services:
  clintwin:
    build: ./clintwin
    expose:
      - "8000"
    links:
      - elasticsearch:elasticsearch
    volumes:
      - type: bind
        source: ./clintwin
        target: /clintwin
    #env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py migrate  
    command: python ./clintwin/manage.py runserver 0.0.0.0:8000

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - clintwin:clintwin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
       - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
#  web-django:
  web-static:
  es_data:
