# Generated by Django 3.0.4 on 2020-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_merge_20200407_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionSchema',
        ),
    ]
