# Generated by Django 3.0.4 on 2020-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='current_recruitment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Recruitment'),
        ),
    ]
