# Generated by Django 3.0.5 on 2020-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0011_auto_20200409_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='status',
            field=models.CharField(default='Draft', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
