# Generated by Django 3.0.4 on 2020-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0015_clinicaltrialcriteriaresponse_last_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrialcriteriaresponse',
            name='last_answered',
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='last_answered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
