# Generated by Django 3.0.4 on 2020-04-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0018_clinicaltrial_is_virtual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorrequest',
            name='sponsor_id',
        ),
        migrations.AddField(
            model_name='sponsorrequest',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor'),
        ),
    ]
