# Generated by Django 3.0.4 on 2020-04-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0024_auto_20200424_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtrialparticipantresponse',
            name='trial_id',
        ),
        migrations.AlterField(
            model_name='virtualtrialparticipantresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.VirtualTrialParticipantQuestion'),
        ),
    ]
