# Generated by Django 3.0.4 on 2020-04-26 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0028_auto_20200426_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(default='Old Org', max_length=500, verbose_name='Organization Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
