# Generated by Django 3.0.4 on 2020-04-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0030_auto_20200426_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrialEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sponsor.ClinicalTrial')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sponsor.Participant')),
            ],
        ),
    ]
