# Generated by Django 3.0.4 on 2020-04-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0031_clinicaltrialenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtrialparticipantquestion',
            name='trial_id',
        ),
        migrations.AddField(
            model_name='virtualtrialparticipantquestion',
            name='clinical_trial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_questions', to='sponsor.ClinicalTrial'),
            preserve_default=False,
        ),
    ]
