# Generated by Django 3.0.4 on 2020-05-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0040_auto_20200504_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualtrialparticipantresponse',
            old_name='last_answered',
            new_name='answered_on',
        ),
        migrations.AlterUniqueTogether(
            name='virtualtrialparticipantresponse',
            unique_together=set(),
        ),
    ]
