# Generated by Django 3.0.4 on 2020-05-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0041_participantprofile'),
        ('sponsor', '0041_auto_20200504_2151'),
    ]

    operations = [
    ]
