# Generated by Django 3.0.4 on 2020-05-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0047_auto_20200512_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtrialparticipantquestion',
            name='last_asked',
        ),
    ]
