# Generated by Django 3.0.4 on 2020-04-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100, null=True, verbose_name='Trial ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Trial Title')),
                ('objective', models.TextField(null=True, verbose_name='Objective')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('recruitmentStartDate', models.DateField(help_text='MM/DD/YY', null=True, verbose_name='Recruitment Start Date')),
                ('recruitmentEndDate', models.DateField(help_text='MM/DD/YY', null=True, verbose_name='Recruitment End Date')),
                ('enrollmentTarget', models.IntegerField(blank=True, null=True, verbose_name='Enrollment Target')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('followUp', models.TextField(blank=True, null=True, verbose_name='Followup Notes')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Location')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('createdTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Status')),
                ('current_recruitment', models.IntegerField(blank=True, null=True, verbose_name='Current Recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalTrialCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('valueType', models.CharField(max_length=50)),
                ('options', models.TextField()),
                ('searchable', models.BooleanField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='sponsor.ClinicalTrialCriteria')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalTrialCriteriaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('comparison', models.CharField(max_length=50)),
                ('criteriaType', models.CharField(max_length=50)),
                ('negated', models.BooleanField()),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_responses', to='sponsor.ClinicalTrialCriteria')),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sponsor.ClinicalTrial')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('valueType', models.CharField(max_length=50)),
                ('options', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text='Name of Sponsor', max_length=500, verbose_name='Organization Name')),
                ('date_joined', models.DateField(null=True, verbose_name='Date of Registration')),
                ('dateDeregistered', models.DateField(blank=True, null=True, verbose_name='Date of De-Regstration')),
                ('contactPerson', models.CharField(max_length=500, null=True, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_id', models.CharField(max_length=50)),
                ('criterion_req', models.CharField(max_length=200, null=True)),
                ('values', models.CharField(max_length=500, null=True)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField(blank=True, null=True, verbose_name='Question Text')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('nextQuestion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Next Question')),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.ClinicalTrialCriteria')),
                ('responseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.ClinicalTrialCriteriaResponse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=128)),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.ParticipantQuestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_flow', to='sponsor.ParticipantQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sponsor.Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.ParticipantQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='participantquestion',
            name='categories',
            field=models.ManyToManyField(to='sponsor.QuestionCategory'),
        ),
        migrations.CreateModel(
            name='ParticipantBasicHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('weight', models.FloatField(null=True, verbose_name='Weight')),
                ('height', models.FloatField(null=True, verbose_name='Height')),
                ('birth_date', models.DateField(blank=True, help_text='MM/DD/YY', null=True, verbose_name='Date of Birth')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalTrialMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_matches', to='sponsor.ClinicalTrial')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_matches', to='sponsor.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='clinicaltrialcriteria',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sponsor.ParticipantQuestion'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.Sponsor'),
        ),
    ]
