# Generated by Django 3.0.5 on 2020-04-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20200407_2001'),
        ('sponsor', '0002_auto_20200407_1958'),
    ]

    operations = [
    ]
