# Generated by Django 3.0.4 on 2020-03-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20200326_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipantQuestionResponse',
            new_name='ParticipantResponse',
        ),
    ]
