# Generated by Django 3.0.4 on 2020-03-30 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_auto_20200326_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_id', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField()),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_id', models.CharField(max_length=50)),
                ('criterion_req', models.CharField(max_length=200, null=True)),
                ('values', models.CharField(max_length=500, null=True)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='clinicaltrialcriteria',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='sponsor.ClinicalTrialCriteria'),
        ),
        migrations.AddField(
            model_name='clinicaltrialcriteria',
            name='searchable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
