# Generated by Django 3.0.4 on 2020-03-31 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_auto_20200330_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaltrial',
            old_name='created_at',
            new_name='createdTimeStamp',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='currentRecruitment',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='targetRecruitment',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_id',
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='enrollmentTarget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enrollment Target'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='followUp',
            field=models.TextField(blank=True, null=True, verbose_name='Followup Notes'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='objective',
            field=models.CharField(max_length=100, null=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='recruitmentEndDate',
            field=models.DateField(help_text='MM/DD/YY', null=True, verbose_name='Recruitment End Date'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='recruitmentStartDate',
            field=models.DateField(help_text='MM/DD/YY', null=True, verbose_name='Recruitment Start Date'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.Sponsor'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Trial Title'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='trialId',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False, verbose_name='Trial ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contactPerson',
            field=models.CharField(max_length=50, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='dateDeregistered',
            field=models.DateField(blank=True, null=True, verbose_name='Date of De-Regstration'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(default='test', help_text='Name of Sponsor', max_length=50, verbose_name='Organization Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClinicalTrialMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_matches', to='sponsor.ClinicalTrial')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_matches', to='sponsor.Participant')),
            ],
        ),
    ]
