# Generated by Django 3.0.4 on 2020-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_auto_20200331_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='objective',
            field=models.TextField(null=True, verbose_name='Objective'),
        ),
    ]
