# Generated by Django 3.0.4 on 2020-04-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_auto_20200408_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='Trial Title'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of Registration'),
        ),
    ]
