# Generated by Django 3.0.4 on 2020-03-31 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_auto_20200331_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialcriteriaresponse',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.ClinicalTrialCriteria'),
        ),
        migrations.AddField(
            model_name='clinicaltrialcriteriaresponse',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sponsor.ClinicalTrial'),
        ),
    ]
