# Generated by Django 3.0.4 on 2020-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_auto_20200331_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialcriteriaresponse',
            name='comparison',
            field=models.CharField(default='gte', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicaltrialcriteriaresponse',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
