# Generated by Django 3.0.4 on 2020-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_auto_20200331_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='contactPerson',
            field=models.CharField(max_length=500, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(help_text='Name of Sponsor', max_length=500, verbose_name='Organization Name'),
        ),
    ]
