# Generated by Django 3.0.4 on 2020-04-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_delete_questionschema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
