# Generated by Django 3.0.4 on 2020-04-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0010_auto_20200331_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialcriteria',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.ParticipantQuestion'),
        ),
    ]
