# Generated by Django 3.0.4 on 2020-04-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0011_clinicaltrialcriteria_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresponse',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sponsor.Participant'),
        ),
    ]
