# Generated by Django 3.0.4 on 2020-04-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0012_auto_20200409_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialmatch',
            name='match',
            field=models.BooleanField(null=True),
        ),
    ]
