# Generated by Django 3.0.4 on 2020-04-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0013_auto_20200402_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrialcriteriaresponse',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_responses', to='sponsor.ClinicalTrialCriteria'),
        ),
    ]
