# Generated by Django 3.0.4 on 2020-04-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0014_auto_20200414_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialcriteriaresponse',
            name='last_answered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
