# Generated by Django 3.0.4 on 2020-04-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0014_auto_20200403_0018'),
        ('sponsor', '0013_auto_20200403_0822'),
    ]

    operations = [
    ]
