# Generated by Django 3.0.5 on 2020-04-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0015_merge_20200405_1237'),
        ('sponsor', '0015_merge_20200403_0308'),
    ]

    operations = [
    ]
