# Generated by Django 3.0.4 on 2020-04-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0015_merge_20200403_0308'),
        ('sponsor', '0015_merge_20200405_1237'),
    ]

    operations = [
    ]
