# Generated by Django 3.0.4 on 2020-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0016_merge_20200405_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='current_recruitment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Recruitment'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='height',
            field=models.FloatField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Lasst Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
    ]
