# Generated by Django 3.0.4 on 2020-04-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0017_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='is_virtual',
            field=models.BooleanField(null=True),
        ),
    ]
