# Generated by Django 3.0.5 on 2020-04-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0017_auto_20200405_1956'),
        ('sponsor', '0016_merge_20200405_1850'),
    ]

    operations = [
    ]
