# Generated by Django 3.0.4 on 2020-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0018_merge_20200405_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaltrial',
            old_name='trialId',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
