# Generated by Django 3.0.4 on 2020-04-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0020_auto_20200406_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=128)),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.ParticipantQuestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_flow', to='sponsor.ParticipantQuestion')),
            ],
        ),
    ]
