# Generated by Django 3.0.4 on 2020-04-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0021_auto_20200423_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTrialParticipantQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('valueType', models.CharField(max_length=50)),
                ('options', models.TextField()),
                ('categories', models.ManyToManyField(to='sponsor.QuestionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTrialParticipantResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('last_answered', models.DateTimeField(auto_now=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_responses', to='sponsor.Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.ParticipantQuestion')),
            ],
            options={
                'unique_together': {('question', 'participant')},
            },
        ),
    ]
