# Generated by Django 3.0.4 on 2020-04-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0021_questionflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Trial ID'),
        ),
    ]
