# Generated by Django 3.0.4 on 2020-04-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0022_virtualtrialparticipantquestion_virtualtrialparticipantresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantquestion',
            name='trial_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_trial_id', to='sponsor.ClinicalTrial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='trial_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response_trial_id', to='sponsor.ClinicalTrial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualtrialparticipantquestion',
            name='trial_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='virtualquestion_trial_id', to='sponsor.ClinicalTrial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualtrialparticipantresponse',
            name='trial_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='virtualresponse_trial_id', to='sponsor.ClinicalTrial'),
            preserve_default=False,
        ),
    ]
