# Generated by Django 3.0.4 on 2020-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0022_auto_20200407_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='custom_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Trial ID'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
