# Generated by Django 3.0.4 on 2020-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0022_auto_20200407_0223'),
    ]

    operations = [
    ]
