# Generated by Django 3.0.4 on 2020-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0027_auto_20200425_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='is_virtual',
            field=models.BooleanField(help_text='Do you plan to administer this trial online?', null=True, verbose_name='Virtual Trial'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(max_length=500, verbose_name='Organization Name'),
        ),
    ]
