# Generated by Django 3.0.4 on 2020-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0029_auto_20200426_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtrialparticipantquestion',
            name='categories',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='Open', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='recruitmentEndDate',
            field=models.DateField(null=True, verbose_name='Recruitment End Date'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='recruitmentStartDate',
            field=models.DateField(null=True, verbose_name='Recruitment Start Date'),
        ),
    ]
