# Generated by Django 3.0.4 on 2020-04-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0033_auto_20200429_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorrequest',
            name='status',
            field=models.CharField(default='Open', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
