# Generated by Django 3.0.4 on 2020-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0035_auto_20200501_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
