# Generated by Django 3.0.4 on 2020-05-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0036_participant_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='state',
            new_name='basic_health',
        ),
    ]
