# Generated by Django 3.0.4 on 2020-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0037_auto_20200501_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrialmatch',
            name='expressed_interest',
            field=models.BooleanField(null=True),
        ),
    ]
