# Generated by Django 3.0.4 on 2020-05-02 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0038_clinicaltrialmatch_expressed_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorrequest',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
