# Generated by Django 3.0.4 on 2020-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0043_auto_20200507_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantbasichealth',
            name='gender',
        ),
        migrations.AddField(
            model_name='participantbasichealth',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Sex'),
        ),
    ]
