# Generated by Django 3.0.4 on 2020-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0045_auto_20200507_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='has_tasks',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='is_archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='virtualtrialparticipantquestion',
            name='frequency',
            field=models.DurationField(null=True),
        ),
    ]
