# Generated by Django 3.0.4 on 2020-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0046_auto_20200510_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='has_tasks',
        ),
        migrations.AddField(
            model_name='virtualtrialparticipantquestion',
            name='last_asked',
            field=models.DateTimeField(null=True),
        ),
    ]
