# Generated by Django 3.0.4 on 2020-05-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0048_remove_virtualtrialparticipantquestion_last_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtrialparticipantresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_responses', to='sponsor.VirtualTrialParticipantQuestion'),
        ),
    ]
