# Generated by Django 3.0.4 on 2020-05-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0049_auto_20200512_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtrialparticipantresponse',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
